# Midterm preparation
## Problem set 6, ex 1

In [1]:
import pulp

Lp1 = pulp.LpProblem("My_LP_1", pulp.LpMaximize)

x1 = pulp.LpVariable('x1', lowBound=0, cat=pulp.LpContinuous)
x2 = pulp.LpVariable('x2', lowBound=0, cat=pulp.LpContinuous)
x3 = pulp.LpVariable('x3', lowBound=0, cat=pulp.LpContinuous)

Lp1 += 2*x1 + 3*x2 + x3

Lp1 += x1 + x2 + x3 <= 40
Lp1 += 2*x1 + x2 - x3 >= 10
Lp1 += 0*x1 - x2 + x3 >= 10

In [2]:
print(Lp1)

My_LP_1:
MAXIMIZE
2*x1 + 3*x2 + 1*x3 + 0
SUBJECT TO
_C1: x1 + x2 + x3 <= 40

_C2: 2 x1 + x2 - x3 >= 10

_C3: - x2 + x3 >= 10

VARIABLES
x1 Continuous
x2 Continuous
x3 Continuous



In [3]:
Lp1.solve()

1

In [4]:
print(x1.value())
print(x2.value())
print(x3.value())

10.0
10.0
20.0


# Solve by hand

In [5]:
# Import the module
import numpy as np

# Implement the pivot function
def pivot(T,i,k):
    # Create a copy of the tableau
    T_pivot = np.copy(T)
    
    # Step (i)
    # We divide the i-th row elementwise by the value of a_ik
    T_pivot[i,:] = T[i,:] / T[i,k]
    
    # Step (ii)
    # Note: for-loops can be interchanged
    # We iterate through each column (l = 1,...,n+m)
    for l in range(0,T.shape[1]):
        # In the column we iterate through each row, but skip row i (j=/=i,j=1,...,m)
        for j in range(0,T.shape[0]):
            if(j!=i):
                # We compute the new value
                T_pivot[j,l] = T[j,l] - T[j,k] * T[i,l] / T[i,k]
    
    return T_pivot 

In [10]:
#Add a header
header_org = np.array(['z','y1','y2','y3','x1','x2','x3','x0',' 1']) 

#Intialize T0
T0 = np.matrix([
    [0, 0, 0, 0, 0, 0, 0, 1, 0],
    [1, 0, 0, 0,-2,-3,-1, 0, 0],
    [0, 1, 0, 0, 1, 1, 1,-1,40],
    [0, 0, 1, 0,-2,-1, 1,-1,-10],
    [0, 0, 0, 1, 0, 1,-1,-1,-10]
],dtype=float)
print(T0)

[[  0.   0.   0.   0.   0.   0.   0.   1.   0.]
 [  1.   0.   0.   0.  -2.  -3.  -1.   0.   0.]
 [  0.   1.   0.   0.   1.   1.   1.  -1.  40.]
 [  0.   0.   1.   0.  -2.  -1.   1.  -1. -10.]
 [  0.   0.   0.   1.   0.   1.  -1.  -1. -10.]]


In [11]:
T1 = pivot(T0, 3, 7)
print("", header_org)
print(T1)

 ['z' 'y1' 'y2' 'y3' 'x1' 'x2' 'x3' 'x0' ' 1']
[[  0.   0.   1.   0.  -2.  -1.   1.   0. -10.]
 [  1.   0.   0.   0.  -2.  -3.  -1.   0.   0.]
 [  0.   1.  -1.   0.   3.   2.   0.   0.  50.]
 [ -0.  -0.  -1.  -0.   2.   1.  -1.   1.  10.]
 [  0.   0.  -1.   1.   2.   2.  -2.   0.   0.]]


In [12]:
T2 = pivot(T1, 4, 4)
print("", header_org)
print(T2)

 ['z' 'y1' 'y2' 'y3' 'x1' 'x2' 'x3' 'x0' ' 1']
[[  0.    0.    0.    1.    0.    1.   -1.    0.  -10. ]
 [  1.    0.   -1.    1.    0.   -1.   -3.    0.    0. ]
 [  0.    1.    0.5  -1.5   0.   -1.    3.    0.   50. ]
 [ -0.   -0.    0.   -1.    0.   -1.    1.    1.   10. ]
 [  0.    0.   -0.5   0.5   1.    1.   -1.    0.    0. ]]


In [14]:
T3 = pivot(T2, 3, 6)
print("", header_org)
print(T3)
print("Feasible!")

 ['z' 'y1' 'y2' 'y3' 'x1' 'x2' 'x3' 'x0' ' 1']
[[ 0.   0.   0.   0.   0.   0.   0.   1.   0. ]
 [ 1.   0.  -1.  -2.   0.  -4.   0.   3.  30. ]
 [ 0.   1.   0.5  1.5  0.   2.   0.  -3.  20. ]
 [-0.  -0.   0.  -1.   0.  -1.   1.   1.  10. ]
 [ 0.   0.  -0.5 -0.5  1.   0.   0.   1.  10. ]]
Feasible!


In [28]:
header_org2 = np.array(['z',' y1','y2','y3','x1','x2','x3','1']) 

T4 = np.matrix([
    [1, 0,-1,-2,0,-4,0,30],
    [0,1,0.5,1.5,0,2,0,20],
    [0,0,0,-1,0,-1,1,10],
    [0,0,-0.5,-0.5,1,0,0,10]
],dtype=float)
print("", header_org2)
print(T4)

 ['z' ' y1' 'y2' 'y3' 'x1' 'x2' 'x3' '1']
[[ 1.   0.  -1.  -2.   0.  -4.   0.  30. ]
 [ 0.   1.   0.5  1.5  0.   2.   0.  20. ]
 [ 0.   0.   0.  -1.   0.  -1.   1.  10. ]
 [ 0.   0.  -0.5 -0.5  1.   0.   0.  10. ]]


In [29]:
T5 = pivot(T4, 1, 5)
print("", header_org2)
print(T5)
print("optimal!")

 ['z' ' y1' 'y2' 'y3' 'x1' 'x2' 'x3' '1']
[[ 1.    2.    0.    1.    0.    0.    0.   70.  ]
 [ 0.    0.5   0.25  0.75  0.    1.    0.   10.  ]
 [ 0.    0.5   0.25 -0.25  0.    0.    1.   20.  ]
 [ 0.    0.   -0.5  -0.5   1.    0.    0.   10.  ]]
optimal!


Optimal solution: $(x_1,x_2,x_3)^* = (10, 20, 10)$